"""initial schema

Revision ID: 273cedc23a30
Revises: 
Create Date: 2026-10-04 17:05:32.042100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273cedc23a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_code', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_route_code'), 'routes', ['route_code'], unique=False)
    op.create_table('stops',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=True),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('predicted_time', sa.DateTime(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'stop_id', name='uq_observation_trip_stop')
    )
    op.create_index('ix_observations_route_time', 'observations', ['route_id', 'observed_at'], unique=False)
    op.create_index('ix_observations_stop_time', 'observations', ['stop_id', 'observed_at'], unique=False)
    op.create_table('scheduled_departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_id', 'day_type', 'departure_time', name='uq_scheduled_departure')
    )
    op.create_index('ix_scheduled_departures_lookup', 'scheduled_departures', ['route_id', 'stop_id', 'day_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_departures_lookup', table_name='scheduled_departures')
    op.drop_table('scheduled_departures')
    op.drop_index('ix_observations_stop_time', table_name='observations')
    op.drop_index('ix_observations_route_time', table_name='observations')
    op.drop_table('observations')
    op.drop_table('stops')
    op.drop_index(op.f('ix_routes_route_code'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
